# -*- coding: utf-8 -*-
"""Regenerate the file:// compatible progress page from illustration-review.json."""
from pathlib import Path
from html import escape as esc
from collections import Counter
import json, hashlib
P=Path(__file__).resolve().parent
D=json.loads((P/'illustration-review.json').read_text())
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def url(asset): return '../../participatory-growth-frame-studies/'+asset
rules_changed=any(not (P/r).exists() or sha(P/r)!=h for r,h in D['audit']['referenceHashes'].items())
cards=[]; counts=Counter(); tags=Counter(); finals=0; stale=0
detail_count=sum(e['currentAudit']['reviewLevel']=='原寸＋一覧確認' for e in D['entries'])
for e in D['entries']:
 a=e['currentAudit']; path=(P/url(e['asset'])).resolve(); current=sha(path); changed=current!=a['imageSha256'] or rules_changed
 status='要再点検' if changed else a['status']; stale+=int(changed);counts[a['animal']]+=1;tags.update(a['tags']);finals+=int(status=='完了' and a['stages']['finalReview']=='完了')
 ref=url(e['asset'])+'?asset='+current[:12]; ident=e['asset'].removesuffix('.png'); seq=a['sequence'];stage=''.join('<li>'+esc(k)+'：'+esc(v)+'</li>' for k,v in [('一次点検',a['stages']['visualReview']),('人物・動物の形',a['stages']['geometry']),('背景',a['stages']['background']),('配色',a['stages']['color']),('最終確認',a['stages']['finalReview'])]);issues=''.join('<span class="tag">'+esc(t)+'</span>' for t in a['tags'])
 applied=a.get('revisionApplied')
 preview_html=('<h4>今回の更新内容</h4><p>'+esc(applied['note'])+'</p>') if applied else ''
 human=a.get('humanShapeAudit')
 if human: preview_html+='<h4>51a0fe5 人物造形の点検</h4><p>'+esc(human['level']+'：'+human['note'])+'</p>'
 plan=a.get('detailedPlan',[])
 plan_html=('<details open><summary>個別の修正計画</summary><ol>'+''.join('<li><b>'+esc(v['focus'])+'</b>：'+esc(v['action'])+'</li>' for v in plan)+'</ol></details>') if plan else ''
 history=''.join('<li>'+esc(h['date']+' '+h['event'])+'</li>' for h in a['history'])
 cards.append(f'''<article id="{ident}" data-animal="{a['animal']}" data-tags="{esc(' '.join(a['tags']))}" data-priority="{a['priority']}" data-status="{status}" data-search="{esc(e['title']+' '+e['asset']+' '+a['observation'])}"><div class="cardtop"><span>組 {a['batch']:02d} · {seq:03d}</span><b>{a['priority']} / {status}</b></div><a class="picture" href="{ref}" target="_blank" rel="noopener"><img loading="lazy" decoding="async" src="{ref}" alt="{esc(e['title'])}" width="1254" height="1254"></a><h3>{esc(e['title'])}</h3><small>{esc(e['asset'])}</small><div class="tags">{issues}<span class="tag">配色は共通工程</span></div><p>{esc(a['observation'])}</p><p class="level">{esc(a['reviewLevel'])} · 使用 {e['usageCount']} 枠</p>{preview_html}{plan_html}<details><summary>進捗・次の作業</summary><ul>{stage}</ul><p>{esc(a['nextAction'])}</p><p>{esc(a['geometryCheck'])}</p><p>最終検証：{esc(str(a.get('verification') or '数値適合・最終掲載サイズは未検証'))}</p><p>確認対象 SHA256：<code>{a['imageSha256'][:12]}</code>{' ／画像または基準が変更されています。再点検が必要です。' if changed else ''}</p><ul>{history}</ul><h4>以前の制作記録</h4><p>{esc(e.get('status',''))}：{esc(e.get('notes','') or '個別記録なし')}</p><p>以前の記録に含まれる旧色・旧ルールは、現在の指示ではありません。</p></details></article>''')
options=lambda values: ''.join('<option>'+esc(v)+'</option>' for v in values)
common=''.join('<li>'+esc(v)+'</li>' for v in D['audit']['commonActions'])
page='''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>成長イラストの点検と修正進捗 | Hugmap</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f2ed;color:#291712;font:15px/1.75 system-ui,sans-serif}main{max-width:1450px;margin:auto;padding:32px 24px 80px}a{color:#795143}h1{font-size:30px;line-height:1.4}h2{font-size:21px}h3{font-size:17px;margin:14px 0 2px}p{margin:10px 0}header>p{max-width:950px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.metric,section.panel{background:#fff;border:1px solid #e4d9cf;border-radius:12px;padding:18px}.metric strong{display:block;font-size:28px}.metric span{font-size:12px}.note{border-left:3px solid #a77c65;padding:10px 16px;background:#fffaf2}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.summary h3{margin:0}.panel{margin-bottom:22px}.controls{display:flex;flex-wrap:wrap;gap:12px;align-items:end}.controls label{font-size:12px;display:grid;gap:4px}input,select,button{font:inherit;padding:9px 12px;border:1px solid #cab9ab;border-radius:6px;background:#fff;color:#291712}input{min-width:220px}button{cursor:pointer}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}article{min-width:0;padding:16px;background:white;border:1px solid #ded4ca;border-radius:12px;scroll-margin-top:20px}.cardtop{display:flex;justify-content:space-between;font-size:12px;gap:8px}.cardtop b{color:#7d2741}.picture{display:block;margin-top:12px;background:#fffcf7}.picture img{display:block;width:100%;height:auto;aspect-ratio:1;object-fit:contain}small,code{overflow-wrap:anywhere;font-size:11px;color:#76675d}.tags{display:flex;gap:5px;flex-wrap:wrap;margin:12px 0}.tag{font-size:11px;background:#f1e9df;padding:3px 7px;border-radius:4px}article p{font-size:13px}.level{color:#78695e}details{border-top:1px solid #e5dbd2;padding:10px 0}summary{cursor:pointer}li{margin:6px 0}.refs{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.refs img{width:100%;height:220px;object-fit:contain;background:white}.refs figure{margin:0}.refs figcaption{font-size:12px}.progress{height:8px;background:#e9e0d8;border-radius:8px;overflow:hidden}.progress span{display:block;height:100%;background:#a77c65}#shown{font-size:13px}[hidden]{display:none!important}@media(max-width:1000px){.grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){main{padding:20px 12px}.grid,.summary,.refs{grid-template-columns:1fr}.metrics{grid-template-columns:1fr 1fr}h1{font-size:25px}.controls label{width:100%}}@media print{.controls,button{display:none}.grid{display:block}article{break-inside:avoid;margin-bottom:20px}article .picture img{max-height:300px}}
</style></head><body><main><header><a href="index.html">← キャラクター設定集</a> · <a href="../../participatory-growth-frames/stage-illustration-inventory-review.html">Development一覧</a><h1>成長イラストの点検と修正進捗</h1><p>子どもの動作を主役に、人物・動物・背景を揃える。3枚ずつ修正し、変更した画像をこの一覧へ反映します。</p><p>更新：2026-09-20 · 対象：137掲載枠／重複を除く120枚</p></header>'''
page+=f'''<div class="metrics"><div class="metric"><strong>120 / 120</strong><span>一覧で一次点検済み</span></div><div class="metric"><strong>{detail_count} / 120</strong><span>今回、原寸でも確認</span></div><div class="metric"><strong>{finals} / 120</strong><span>現行仕様で最終確認完了</span><div class="progress"><span style="width:{finals/120*100}%"></span></div></div><div class="metric"><strong>{stale}</strong><span>画像・基準の変更により再点検</span></div></div><p class="note">全120枚の一次点検が完了しました。これまでに計61枚を元のファイル名で更新しました。各カードには現在の画像を表示します。全画像の原寸照合・三面図との重ね合わせ・線幅の測定は未完了です。過去の「修正済み」は現行ガイドラインへの合格を意味しません。</p>
<section class="panel"><h2>全体で揃えること</h2><div class="summary"><div><h3>Gen · {counts['gen']}枚</h3><p>草花の密度、地面の描き込み、黄色い光の輪が混在。歩行・接地や必要な遊具は残して背景を整理。</p></div><div><h3>Luke · {counts['luke']}枚</h3><p>幼児の髪・頭身、机下の広い影に差。指先と道具の接点を保ち、人物を先に整える。</p></div><div><h3>Mimo · {counts['mimo']}枚</h3><p>卵形の頭、冠羽、胴・翼・脚の比率に差。正面・横向き・座位をそれぞれ原図へ照合。</p></div></div><details><summary>共通の基準と参照元</summary><ul>{common}</ul><p>{esc(D['audit']['referenceAuthority'])}</p><div class="refs"><figure><a href="assets/user-approved-turnaround.png"><img loading="lazy" src="assets/user-approved-turnaround.png" alt="造形の原三面図"></a><figcaption>動物の造形。画像内の旧色は採用しない。</figcaption></figure><figure><img loading="lazy" src="assets/child-toddlers-simple-hair-v1.png" alt="幼児の造形見本"><figcaption>幼児の髪・身体。姿勢は場面に合わせる。</figcaption></figure><figure><img loading="lazy" src="assets/adult-standard-mixed-hair-v2.png" alt="大人の造形見本"><figcaption>大人の髪・身体。色はJSON仕様を優先。</figcaption></figure></div><p><a href="animal-line-style.json">動物の線</a> · <a href="human-silhouette-style.json">人物の線・髪</a> · <a href="brand-colors.json">配色</a> · <a href="growth-scene-design-rules.json">シーン要件</a></p></details></section>
<section class="panel"><h2>51a0fe5：人物造形の再点検</h2><p>対象18枚を一覧で見本と照合し、大きな差があった3枚を原寸確認して同名更新。残り15枚の所見も各カードへ記録。その後、ピースの足元・ばんざい模倣の手と髪・AACの大人の座位を追加修正しました。年齢や体型は髪の有無だけで決めません。線色・線幅の数値適合と最終掲載サイズの確認は未完了です。</p></section><section class="panel"><h2>更新画像の確認</h2><p>今回更新：<a href="#luke-frame-page-turn">055 ページめくり</a>・<a href="#luke-frame-paper-collage">056 貼り絵</a>・<a href="#luke-frame-paper-fold">057 折り紙</a>。手元と姿勢を保ち、結び髪の女の子、淡い家具と小さな飾りを反映。Lukeの白い体と胸上Uを確認。スカーフ内部線は継続確認。残課題と最終適合は各カードで継続確認。</p><p><a href="#mimo-frame-noticing-letters">090 文字への気づき</a>：見上げる小鳥と人物の髪 ／ <a href="#mimo-frame-turn-taking-cards">108 順番カード</a>：座ってジュースを飲む待機動作・大人の線 ／ <a href="#relationship-frame-lift-play">116 たかい、たかい</a>：人物の接点・線の階層・背景光。</p><p>038〜057・059・078〜111・113・115〜119は画像更新済みです。残課題を確認しながら、3枚ずつ進めます。各画像は「人物・接点 → 動物の形 → 背景 → 配色 → 縮小確認」の順に進めます。配色だけで完了と判断した画像はまだありません。</p></section>
<section class="panel"><h2>120枚の修正一覧</h2><div class="controls"><label>検索<input id="search" type="search" placeholder="場面名・ファイル名・修正内容"></label><label>動物<select id="animal"><option value="">すべて</option><option value="gen">Gen</option><option value="luke">Luke</option><option value="mimo">Mimo</option></select></label><label>課題<select id="issue"><option value="">すべて</option>{options(tags.keys())}</select></label><label>優先度<select id="priority"><option value="">すべて</option>{options(['先行3枚','優先','通常'])}</select></label><label>進捗<select id="status"><option value="">すべて</option>{options(['修正待ち','修正中','再確認待ち','完了','要再点検'])}</select></label><button id="reset" type="button">絞り込み解除</button></div><p id="shown" role="status" aria-live="polite">120枚表示。組番号は固定で、各組3枚です。画像を押すと原寸を開きます。</p></section><div class="grid">'''+''.join(cards)+'''</div>
<section class="panel"><h2>更新履歴と運用</h2><p>2026-09-20：全120枚を一次点検し、各画像の修正内容・優先度・工程を登録。原寸追加確認3枚。最終確認完了0枚。</p><p>次の画像修正時は、画像・個別進捗・確認記録を一緒に更新します。変更された画像または基準は、再生成時に「要再点検」と表示されます。</p><p><a href="illustration-review.json">現在の進捗データと制作履歴</a> · <a href="illustration-review-history.html">書き換え前のレビュー記録</a> · <a href="illustration-review-workflow.md">更新手順</a></p></section></main>
<script>
const controls=['search','animal','issue','priority','status'].map(id=>document.getElementById(id));
const cards=Array.from(document.querySelectorAll('article[data-animal]'));
function filter(){const [q,animal,issue,priority,status]=controls.map(e=>e.value.trim());let count=0;for(const card of cards){const d=card.dataset;const ok=(!q||d.search.toLowerCase().includes(q.toLowerCase()))&&(!animal||d.animal===animal)&&(!issue||d.tags.split(' ').includes(issue))&&(!priority||d.priority===priority)&&(!status||d.status===status);card.hidden=!ok;if(ok)count++;}document.getElementById('shown').textContent=count+' / '+cards.length+'枚表示。組番号は固定（各組3枚）。画像を押すと原寸を開きます。';}
controls.forEach(e=>e.addEventListener('input',filter));document.getElementById('reset').addEventListener('click',()=>{controls.forEach(e=>e.value='');filter();});
function revealHash(){let id;try{id=decodeURIComponent(location.hash.slice(1));}catch{return;}const node=document.getElementById(id);if(node&&node.matches('article')){controls.forEach(e=>e.value='');filter();node.scrollIntoView({block:'start'});}}
window.addEventListener('hashchange',revealHash);revealHash();
</script></body></html>'''
(P/'illustration-review.html').write_text(page)
print(f'Built {len(cards)} cards; {finals} complete; {stale} stale')
